package com.bibliotech.entity;
// Generated 12 avr. 2024, 20:17:47 by Hibernate Tools 5.3.20.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book", catalog = "bibliotech")
public class Book implements java.io.Serializable {

	private Integer uid;
	private String title;
	private String description;
	private String isbn;
	private Integer nbPages;
	private Date published;
	private Boolean illustrations;
	private byte[] cover;
	private Date majDate;
	private Set<Author> authors = new HashSet<Author>();
	private Set<Category> categories = new HashSet<Category>();

	public Book() {
	}

	public Book(String title, Date majDate) {
		this.title = title;
		this.majDate = majDate;
	}

	public Book(String title, String description, String isbn, Integer nbPages, Date published, Boolean illustrations,
			byte[] cover, Date majDate, Set<Author> authors, Set<Category> categories) {
		this.title = title;
		this.description = description;
		this.isbn = isbn;
		this.nbPages = nbPages;
		this.published = published;
		this.illustrations = illustrations;
		this.cover = cover;
		this.majDate = majDate;
		this.authors = authors;
		this.categories = categories;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "uid", unique = true, nullable = false)
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 2000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "isbn")
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "nb_pages")
	public Integer getNbPages() {
		return this.nbPages;
	}

	public void setNbPages(Integer nbPages) {
		this.nbPages = nbPages;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "published", length = 10)
	public Date getPublished() {
		return this.published;
	}

	public void setPublished(Date published) {
		this.published = published;
	}

	@Column(name = "illustrations")
	public Boolean getIllustrations() {
		return this.illustrations;
	}

	public void setIllustrations(Boolean illustrations) {
		this.illustrations = illustrations;
	}

	@Column(name = "cover")
	public byte[] getCover() {
		return this.cover;
	}

	public void setCover(byte[] cover) {
		this.cover = cover;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "maj_date", nullable = false, length = 19)
	public Date getMajDate() {
		return this.majDate;
	}

	public void setMajDate(Date majDate) {
		this.majDate = majDate;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "author_book", catalog = "bibliotech", joinColumns = {
			@JoinColumn(name = "uid_book", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "uid_author", nullable = false, updatable = false) })
	public Set<Author> getAuthors() {
		return this.authors;
	}

	public void setAuthors(Set<Author> authors) {
		this.authors = authors;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "book_category", catalog = "bibliotech", joinColumns = {
			@JoinColumn(name = "uid_book", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "uid_category", nullable = false, updatable = false) })
	public Set<Category> getCategories() {
		return this.categories;
	}

	public void setCategories(Set<Category> categories) {
		this.categories = categories;
	}

}
