package com.wajac.bibliotech.entity;
//Generated 12 avr. 2024, 20:17:47 by Hibernate Tools 5.3.20.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.wajac.bibliotech.session.EntityUID;

/**
 * Author generated by hbm2java
 */
@Entity
@Table(name = "author", catalog = "bibliotech")
public class Author implements java.io.Serializable, EntityUID {

	private Integer uid;
	private String civility;
	private Character gender;
	private String firstName;
	private String lastName;
	private String address1;
	private String address2;
	private String zipCode;
	private String city;
	private String country;
	private Date majDate;
	private Set<Book> books = new HashSet<Book>();

	public Author() {
	}

	public Author(String firstName, String lastName, Date majDate) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.majDate = majDate;
	}

	public Author(String civility, Character gender, String firstName, String lastName, String address1,
			String address2, String zipCode, String city, String country, Date majDate, Set<Book> books) {
		this.civility = civility;
		this.gender = gender;
		this.firstName = firstName;
		this.lastName = lastName;
		this.address1 = address1;
		this.address2 = address2;
		this.zipCode = zipCode;
		this.city = city;
		this.country = country;
		this.majDate = majDate;
		this.books = books;
	}

	public Author(Integer uid, String civility, Character gender, String firstName, String lastName, String address1,
			String address2, String zipCode, String city, String country, Date majDate, Set<Book> books) {
		this.uid = uid;
		this.civility = civility;
		this.gender = gender;
		this.firstName = firstName;
		this.lastName = lastName;
		this.address1 = address1;
		this.address2 = address2;
		this.zipCode = zipCode;
		this.city = city;
		this.country = country;
		this.majDate = majDate;
		this.books = books;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "uid", unique = true, nullable = false)
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Column(name = "civility", length = 15)
	public String getCivility() {
		return this.civility;
	}

	public void setCivility(String civility) {
		this.civility = civility;
	}

	@Column(name = "gender", length = 1)
	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	@Column(name = "first_name", nullable = false, length = 64)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false, length = 64)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "address1", length = 64)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address2", length = 64)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "zip_code", length = 15)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "city", length = 64)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "country", length = 64)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "maj_date", nullable = false, length = 19)
	public Date getMajDate() {
		return this.majDate;
	}

	public void setMajDate(Date majDate) {
		this.majDate = majDate;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "author_book", catalog = "bibliotech", joinColumns = {
			@JoinColumn(name = "uid_author", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "uid_book", nullable = false, updatable = false) })
	public Set<Book> getBooks() {
		return this.books;
	}

	public void setBooks(Set<Book> books) {
		this.books = books;
	}

}
