package com.wajac.bibliotech.entity;
//Generated 12 avr. 2024, 20:17:47 by Hibernate Tools 5.3.20.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import com.wajac.bibliotech.session.EntityUID;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "bibliotech")
public class Category implements java.io.Serializable, EntityUID {

	private Integer uid;
	private String code;
	private String label;
	private Set<Book> books = new HashSet<Book>();

	public Category() {
	}

	public Category(String code, String label) {
		this.code = code;
		this.label = label;
	}

	public Category(String code, String label, Set<Book> books) {
		this.code = code;
		this.label = label;
		this.books = books;
	}

	public Category(Integer uid, String code, String label, Set<Book> books) {
		this.uid = uid;
		this.code = code;
		this.label = label;
		this.books = books;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "uid", unique = true, nullable = false)
	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	@Column(name = "code", nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "label", nullable = false, length = 64)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "book_category", catalog = "bibliotech", joinColumns = {
			@JoinColumn(name = "uid_category", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "uid_book", nullable = false, updatable = false) })
	public Set<Book> getBooks() {
		return this.books;
	}

	public void setBooks(Set<Book> books) {
		this.books = books;
	}

}
